import { Inter } from "next/font/google";
import 'bulma/css/bulma.min.css';
import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NICKFLIX",
  description: "Generated by NICKFLIX",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
