import { Inter } from "next/font/google";
import "bulma/css/bulma.min.css";
import "./globals.scss";

import {Providers} from './GlobalRedux/providers'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NICKFLIX",
  description: "Generated by NICKFLIX",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
